### PR TITLE
Set a Variable QMAKE in the makefile to direct build on Fedora 32, wh…

### PR DESCRIPTION
**Pull request by TahomaSoft**
Set a Variable QMAKE in the makefile to direct build on Fedora 32, where 'qmake' doesn't exist, but qmake-qt5 (and qmake-qt4) does.

### CODE REVIEW

**Comment by MasterQ32** [comment]
Can you make it so the variable is set to `qmake` by-default? `qmake-qt5` is not available on a lot of distros. Can you also add build hints to `BUILDING.md` to explain what packages are required on fedora and how to build it there?

**Comment by TahomaSoft** [comment]
Certainly! Already started doing something similar after I saw the automated build failure notification. Will do and update my fork of your repo sometime later today.

Regards,

Erik

**Comment by TahomaSoft** [comment]
Just made the changes requested.

**Comment by MasterQ32** [comment]
Thanks!

**Pull request merged**
